name: CD Pipeline (Android & iOS)

on:
  push:
    branches:
      - main
      - release

jobs:
  # Android Release Job
  android-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install
          cd android && ./gradlew clean

      - name: Build the Android app
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload APK to Firebase App Distribution (Optional)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_AUTH_TOKEN }}
          groups: testers
          file: android/app/build/outputs/apk/release/app-release.apk

#   # iOS Release Job
#   ios-release:
#     runs-on: macos-latest
#     needs: android-release  # iOS deploy only after Android deploy
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Set up Ruby (for CocoaPods)
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: '2.7'

#       - name: Install Dependencies
#         run: |
#           gem install cocoapods
#           pod install --repo-update
#           npm install

#       - name: Build the iOS app (Release)
#         run: |
#           cd ios
#           xcodebuild clean -workspace YourAppName.xcworkspace -scheme YourAppName -configuration Release
#           xcodebuild archive -workspace YourAppName.xcworkspace -scheme YourAppName -archivePath $PWD/build/YourAppName.xcarchive

#       - name: Export IPA for iOS Release
#         run: |
#           cd ios
#           xcodebuild -exportArchive -archivePath $PWD/build/YourAppName.xcarchive -exportOptionsPlist $PWD/exportOptions.plist -exportPath $PWD/build/YourAppName.ipa

#       - name: Upload to TestFlight
#         env:
#           APPLE_ID: ${{ secrets.APPLE_ID }}
#           APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
#           FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
#         run: |
        #   gem install fastlane
        #   fastlane pilot upload --ipa ios/build/YourAppName.ipa
