name: CI Pipeline (Android & iOS)

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  # Android Build Job
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install
          cd android && ./gradlew clean

      - name: Build the Android app
        run: |
          cd android && ./gradlew assembleRelease

      - name: Run Android Tests (Optional)
        run: |
          cd android && ./gradlew test

  # iOS Build Job
#   ios-build:
#     runs-on: macos-latest  # Use macOS for iOS builds
#     needs: android-build  # Ensures iOS build runs after Android

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Set up Ruby (for CocoaPods)
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: '2.7'

#       - name: Install Dependencies
#         run: |
#           gem install cocoapods
#           pod install --repo-update
#           npm install

    #   - name: Build the iOS app
    #     run: |
    #       cd ios
    #       xcodebuild clean -workspace StarterTemplate.xcworkspace -scheme StarterTemplate -configuration Release
    #       xcodebuild archive -workspace StarterTemplate.xcworkspace -scheme StarterTemplate -archivePath $PWD/build/YourAppName.xcarchive

    #   - name: Run iOS Tests
    #     run: |
    #       cd ios
    #       xcodebuild test -workspace YourAppName.xcworkspace -scheme YourAppName -destination 'platform=iOS Simulator,name=iPhone 12'
